custom_monument_prompts = {
    "Ajanta Caves": [
        "A photo of the Ajanta Caves, featuring ancient Buddhist murals and colorful frescoes painted directly onto the rock walls.",
        "A wide shot of the Ajanta Caves, showing the distinctive horseshoe-shaped rocky gorge and the Waghora River below.",
        "A close-up photo of the Ajanta Caves, highlighting the intricately painted Bodhisattva Padmapani fresco.",
        "A photo of a Chaitya hall inside the Ajanta Caves, featuring carved stone pillars leading to a central, dome-like Buddhist stupa.",
        "An architectural photo of the Ajanta Caves, showing the massive basalt rock-cut entrances with ribbed wooden-style stone ceilings.",
        "A tourist photo of the Ajanta Caves, displaying the ancient stone-carved facades built side-by-side into the steep cliffside.",
        "A photo of the Ajanta Caves interior, showcasing the dimly lit prayer halls covered in detailed, ancient narrative paintings.",
        "A detail shot from the Ajanta Caves, showing the preserved natural pigments of ancient Indian rock art on the walls and ceiling.",
        "A photo of the Ajanta Caves exterior, highlighting the carved columned verandahs overlooking the steep valley.",
        "A photo of the Ajanta Caves, focusing on the large sculpted Buddha statues seated deep inside the dark sanctums.",
        "A wide landscape photo of the Ajanta Caves complex, carved continuously along the curved rocky hillside.",
        "A close-up photograph of the Ajanta Caves, capturing the detailed floral and geometric stone carvings surrounding the entrance portals.",
        "A photo showing the interior of the Ajanta Caves, with light illuminating the ancient Jataka tale paintings.",
        "A photograph of the rock-cut architecture of the Ajanta Caves, featuring rows of heavy stone pillars covered in painted motifs.",
        "A photo of the Ajanta Caves in Maharashtra, showcasing the unique blend of Buddhist stone sculpture and vibrant ancient wall paintings."
    ],
    "Charar-E- Sharif": [
        "A photo of the Charar-E-Sharif, featuring its distinctive Kashmiri wooden architecture and tiered pagoda-like roof.",
        "A close-up of Charar-E-Sharif, highlighting the intricate wooden lattice windows and traditional pinjrakari craftsmanship.",
        "A wide shot of the Charar-E-Sharif shrine, showing its square wooden structure surrounded by the hilly landscape of Kashmir.",
        "A photo of the Charar-E-Sharif, focusing on the tall, pointed metallic spire atop its traditional green-sloped roof.",
        "An architectural photograph of Charar-E-Sharif, showing the unique khatamband wooden ceiling design and timber walls.",
        "A tourist photo of the Charar-E-Sharif, capturing the grand Sufi shrine with its overhanging wooden eaves and balconies.",
        "A photo of the exterior of Charar-E-Sharif, featuring the blend of Islamic and traditional Himalayan timber architectural styles.",
        "A landscape photo of Charar-E-Sharif, standing prominently against the backdrop of the Budgam mountains.",
        "A photo showing the details of the Charar-E-Sharif, focusing on the beautifully carved wooden pillars and arched doorways.",
        "A high-quality image of the Charar-E-Sharif, showcasing the multi-tiered roof structure that defines regional Kashmiri shrines.",
        "A photo of the Charar-E-Sharif shrine complex, showing the main wooden mausoleum and the surrounding open courtyard.",
        "A close-up photo of the Charar-E-Sharif, capturing the warm tones of the timber cladding and the metallic finial on the roof.",
        "A photograph of the historic Charar-E-Sharif, featuring the intricate geometric woodwork that survived its modern reconstruction.",
        "A wide photograph of Charar-E-Sharif, highlighting its prominent, elevated position overlooking the surrounding town.",
        "A photo of the Charar-E-Sharif Sufi shrine, characterized by its square base, prominent wooden columns, and soaring central spire."
    ],
    "Chhota_Imambara": [
        "A photo of the Chhota Imambara in Lucknow, featuring its prominent white dome and golden finials.",
        "A wide shot of the Chhota Imambara, showing the front water channel, fountains, and the black-and-white tessellated courtyard.",
        "A close-up photo of the Chhota Imambara, highlighting the intricate white stucco plasterwork and Arabic calligraphy on the exterior walls.",
        "A photo of the interior of the Chhota Imambara, capturing the stunning array of hanging glass chandeliers that give it the name Palace of Lights.",
        "An architectural photograph of the Chhota Imambara, showing the main white structure flanked by decorative minarets.",
        "A photo of the Chhota Imambara, featuring its gilded domes, elaborate parapets, and Nawabi architectural style.",
        "A tourist photo of the Chhota Imambara, showcasing the reflective water pool leading directly up to the main white arched entrance.",
        "A detail shot of the Chhota Imambara, focusing on the elaborate floral motifs and Quranic verses carved deep into the facade.",
        "A photo of the Chhota Imambara complex, showing the ornate gateway contrasting with the white marble and stucco main building.",
        "A high-quality image of the Chhota Imambara, capturing the silver-framed mirrors and Belgian glass lamps glowing inside the hall.",
        "A photo of the Chhota Imambara's exterior, highlighting the five doorways with multi-foliated arches.",
        "A photograph of the Chhota Imambara, focusing on the golden umbrella-like cupolas (chhatris) crowning the roofline.",
        "A wide shot of the Chhota Imambara, featuring the ornate structural symmetry and the lush green gardens flanking the water stream.",
        "A photo showing the details of the Chhota Imambara, with the striking black and white geometric marble floor in the foreground.",
        "A photo of the Chhota Imambara, characterized by its pristine white facade, golden spires, and intricate Islamic plaster ornamentation."
    ],
    "Ellora Caves": [
        "A photo of the Ellora Caves, featuring the massive monolithic Kailasanatha Temple carved entirely out of a single basalt rock.",
        "A wide shot of the Ellora Caves, showing the vast multi-story rock-cut Hindu, Jain, and Buddhist temples carved into the Charanandri hills.",
        "A close-up photo of the Ellora Caves, highlighting the intricate, life-sized stone sculptures of elephants standing in the courtyard.",
        "A photo of the Ellora Caves, focusing on the dynamic, deep-relief stone carving of Ravana shaking Mount Kailash.",
        "An architectural photograph of the Ellora Caves, showing the massive, freestanding stone pillars and deep structural excavations.",
        "A tourist photo of the Ellora Caves, capturing the immense scale of Cave 16 with its towering rock-cut shikhara (temple tower).",
        "A photo of the Ellora Caves interior, featuring the massive ribbed stone ceilings and large seated statues carved from the bedrock.",
        "A detail shot from the Ellora Caves, showing the highly detailed, unpainted deep-relief stone carvings of deities covering the walls.",
        "A photo of the Ellora Caves complex, highlighting the stark contrast between the dark raw basalt stone and the open-air courtyards.",
        "A photograph of the Ellora Caves, focusing on the ornate, multi-level rock-cut galleries and stone bridges connecting the temples.",
        "A landscape photo of the Ellora Caves, showing the sheer rock face that was excavated downward to create the freestanding monuments.",
        "A close-up of the Ellora Caves, capturing the sharp, precise stonemasonry of the Jain caves' intricately carved pillars (Cave 32).",
        "A photo of the Ellora Caves, featuring the massive freestanding victory pillar (dhwajasthambha) carved directly from the bedrock.",
        "A wide photograph of the Ellora Caves, showing the dramatic shadows cast by the deep, cavernous unpainted rock-cut entrances.",
        "A photo of the Ellora Caves in Maharashtra, characterized by unpainted, raw basalt rock architecture and gigantic monolithic stone sculptures."
    ],
    "Fatehpur Sikri": [
        "A photo of Fatehpur Sikri, showcasing the massive Buland Darwaza built from red sandstone.",
        "A wide shot of the deserted Mughal city of Fatehpur Sikri, featuring expansive red sandstone courtyards.",
        "A close-up of the Panch Mahal in Fatehpur Sikri, a unique five-tiered columnar pavilion.",
        "A photo of the white marble Tomb of Salim Chishti standing out against the red sandstone of Fatehpur Sikri.",
        "An architectural photograph of Fatehpur Sikri, highlighting the intricate red sandstone jali screens and carved brackets.",
        "A tourist photo of the towering Buland Darwaza gate at the entrance of Fatehpur Sikri.",
        "A photo of the Fatehpur Sikri complex, featuring the blending of Islamic and Hindu architectural styles in red stone.",
        "A detail shot from Fatehpur Sikri, showing the ornate pillars of the Diwan-i-Khas with its central lotus throne.",
        "A photo of the Jama Masjid courtyard within the walled city of Fatehpur Sikri.",
        "A high-quality image of the red sandstone pavilions and domed chhatris of Fatehpur Sikri.",
        "A landscape photo of the historic fortified city of Fatehpur Sikri built by Emperor Akbar.",
        "A close-up photograph of the deep red sandstone carvings and geometric patterns at Fatehpur Sikri.",
        "A photo showing the interior courtyards of Fatehpur Sikri, specifically the Anup Talao ornamental pool.",
        "A photograph of the royal palaces of Fatehpur Sikri, characterized by flat roofs and heavy stone brackets.",
        "A photo of Fatehpur Sikri in Uttar Pradesh, dominated by massive Mughal red sandstone structures and monumental gateways."
    ],
    "Gateway of India": [
        "A photo of the Gateway of India, a monumental arch built from yellow basalt rock in Mumbai.",
        "A wide shot of the Gateway of India standing directly on the waterfront of the Arabian Sea.",
        "A close-up photo of the Gateway of India, highlighting its Indo-Saracenic architecture and intricate latticework.",
        "A photo of the Gateway of India, focusing on its central Roman-style triumphal arch and four corner turrets.",
        "An architectural photograph of the Gateway of India, showing the detailed yellow basalt carvings and dome.",
        "A tourist photo of the Gateway of India in Mumbai, with boats and the ocean visible in the background.",
        "A photo of the Gateway of India's exterior, featuring the large central dome and Gujarati-style stone craftsmanship.",
        "A detail shot of the Gateway of India, focusing on the heavy basalt stone columns and arched doorways.",
        "A photo of the Gateway of India plaza, showing the massive stone monument overlooking the harbor.",
        "A high-quality image of the Gateway of India, capturing the warm tones of the yellow basalt stone against the sky.",
        "A photo of the Gateway of India, distinguishing it with its coastal setting and Indo-Islamic architectural blend.",
        "A close-up photograph of the ornate stone turrets atop the Gateway of India monument.",
        "A wide photograph of the Gateway of India, emphasizing its scale as a historic embarkation point by the water.",
        "A photo showing the structural details of the Gateway of India, including the intersecting arches and central dome.",
        "A photo of the Gateway of India, characterized by its yellow basalt construction, waterfront location, and grand archway."
    ],
    "Hawa mahal": [
        "A photo of the Hawa Mahal in Jaipur, featuring its iconic honeycomb-shaped pink sandstone facade.",
        "A wide street-level shot of the Hawa Mahal, showing its five-story pyramidal shape resembling the crown of Krishna.",
        "A close-up photo of the Hawa Mahal, highlighting the hundreds of intricate small windows known as jharokhas.",
        "A photo of the exterior of Hawa Mahal, focusing on the pink and red sandstone carved with delicate white lime motifs.",
        "An architectural photograph of the Hawa Mahal, showing the steep, narrow profile of the Palace of Winds.",
        "A tourist photo of the Hawa Mahal, capturing the dense cluster of overhanging latticed balconies.",
        "A photo of the Hawa Mahal facade, designed specifically to allow royal women to observe street festivals unseen.",
        "A detail shot of the Hawa Mahal, focusing on the delicate pink sandstone jali screens and curved roofs.",
        "A photo of the Hawa Mahal complex, highlighting the Rajput architectural style of the towering front elevation.",
        "A high-quality image of the Hawa Mahal, emphasizing the geometric repetition of its ornate pink windows.",
        "A photo of the Hawa Mahal, showing the contrast of the pink sandstone against the blue sky.",
        "A close-up photograph of the cupolas and domed chhatris capping the intricate facade of the Hawa Mahal.",
        "A wide photograph of the Hawa Mahal from the main road, showing its flat, screen-like architecture.",
        "A photo showing the intricate exterior details of the Hawa Mahal, famous for its cooling breeze architecture.",
        "A photo of the Hawa Mahal, instantly recognizable by its sheer wall of pink sandstone jharokhas and honeycomb design."
    ],
    "Humayun_s Tomb": [
        "A photo of Humayun's Tomb in Delhi, featuring its massive white marble Persian double dome atop a red sandstone body.",
        "A wide shot of Humayun's Tomb, showing the grand Mughal mausoleum centered in a large, geometrically divided Charbagh garden.",
        "A close-up photo of Humayun's Tomb, highlighting the contrast between the red sandstone walls and the white marble inlay borders.",
        "A photo of Humayun's Tomb, focusing on the high central iwan entrance flanked by smaller octagonal chambers.",
        "An architectural photograph of Humayun's Tomb, showing the symmetrical Mughal design that inspired the Taj Mahal.",
        "A tourist photo of Humayun's Tomb, capturing the main structure sitting on a massive, terraced red sandstone platform.",
        "A photo of the exterior of Humayun's Tomb, featuring the ornate chhatris surrounding the central white dome.",
        "A detail shot of Humayun's Tomb, focusing on the delicate stone lattice work covering the arched windows.",
        "A photo of Humayun's Tomb complex, highlighting the reflecting water channels leading up to the main monument.",
        "A high-quality image of Humayun's Tomb, showcasing the octagonal layout and the prominent white marble dome.",
        "A landscape photo of Humayun's Tomb, viewed symmetrically from the end of the Persian-style garden pathway.",
        "A close-up photograph of the red sandstone and white marble geometric patterns decorating the facade of Humayun's Tomb.",
        "A photo showing the grand scale of Humayun's Tomb, an early masterpiece of Mughal garden-tomb architecture.",
        "A wide photograph of Humayun's Tomb, featuring the chamfered corners that give the building its octagonal appearance.",
        "A photo of Humayun's Tomb, strictly characterized by its dominant white marble double dome rising above red sandstone arches."
    ],
    "India_gate": [
        "A photo of India Gate, the massive sandstone war memorial arch in New Delhi.",
        "A wide shot of India Gate at the end of the Rajpath, featuring its grand triumphal arch design.",
        "A close-up of India Gate, showing the inscribed names of soldiers on its sandstone walls.",
        "A photo of the India Gate complex, including the freestanding empty marble canopy cupola behind it.",
        "An architectural photo of India Gate, built from red and pale yellow Bharatpur sandstone.",
        "A tourist photo of India Gate in Delhi, highlighting its prominent central arch and memorial flame.",
        "A photo of India Gate at dusk, showcasing its silhouette as a monumental war memorial.",
        "A detail shot of the top cornice and stepped roof of the India Gate archway.",
        "A photo of the India Gate, distinct from other arches with its Amar Jawan Jyoti eternal flame structure at the base.",
        "A high-quality image of the imposing sandstone India Gate memorial standing in an open plaza.",
        "A photo of India Gate, a 42-meter tall historical archway in the heart of Delhi.",
        "A close-up photograph of the INDIA inscription carved into the top of the India Gate monument.",
        "A wide photograph of the India Gate, emphasizing its monumental scale and symmetrical sandstone architecture.",
        "A photo showing the structural details of India Gate, with its shallow domed bowl at the very top.",
        "A photo of the India Gate memorial, characterized by its sheer sandstone walls and prominent Roman arch style."
    ],
    "Khajuraho": [
        "A photo of the Khajuraho temples, featuring the soaring Nagara-style stone shikharas.",
        "A wide shot of a Khajuraho temple, showing the structure elevated on a high masonry platform.",
        "A close-up photo of Khajuraho, highlighting the densely packed, intricately carved stone figures of apsaras and deities.",
        "A photo of the Khajuraho monuments, famous for the horizontal bands of detailed erotic sculptures on the exterior walls.",
        "An architectural photograph of Khajuraho, showing the cluster of intricately carved sandstone temple towers.",
        "A tourist photo of the Khajuraho Group of Monuments, capturing the warm tones of the sandstone architecture.",
        "A photo of the exterior of a Khajuraho temple, featuring the beautifully sculpted celestial maidens.",
        "A detail shot of Khajuraho, focusing on the deep relief carvings and mithuna sculptures covering the temple base.",
        "A photo of the Khajuraho temple complex, highlighting the Hindu and Jain architectural masterpieces.",
        "A high-quality image of Khajuraho, emphasizing the progressively taller spires leading to the main sanctum.",
        "A photo of the Khajuraho temples, characterized by their lack of enclosure walls and highly ornamented facades.",
        "A close-up photograph of the intricate sandstone statuary and divine figures adorning the walls at Khajuraho.",
        "A wide photograph of Khajuraho, showcasing the perfectly proportioned, mountain-like temple silhouette.",
        "A photo showing the details of the mandapa roof and carved pillars of a Khajuraho temple.",
        "A photo of Khajuraho, universally recognized by its unparalleled density of exquisite human and divine stone sculptures."
    ],
    "Sun Temple Konark": [
        "A photo of the Sun Temple in Konark, shaped like a colossal stone chariot of the Sun God.",
        "A wide shot of the Konark Sun Temple, showing the massive structure built from laterite and chlorite rock.",
        "A close-up photo of the Sun Temple Konark, highlighting one of the 24 gigantic, intricately carved stone chariot wheels.",
        "A photo of the Konark Sun Temple, focusing on the large sculpted stone horses pulling the chariot at the entrance.",
        "An architectural photograph of the Sun Temple Konark, featuring the towering pyramidal jagamohana roof.",
        "A tourist photo of the Konark Sun Temple, capturing the majestic ruins of the ancient Kalinga architecture.",
        "A photo of the exterior of the Konark Sun Temple, showing the walls completely covered in detailed bas-reliefs.",
        "A detail shot of the Sun Temple Konark, focusing on the intricate carvings of musicians and dancers on the platform base.",
        "A photo of the Konark Sun Temple complex, highlighting the massive iron beams used in its structural construction.",
        "A high-quality image of the Sun Temple at Konark, known as the Black Pagoda due to its dark stone appearance.",
        "A photo of the Sun Temple Konark, distinguishing itself with its monumental chariot-shaped temple base.",
        "A close-up photograph of the spokes and hub of the iconic Konark stone wheel.",
        "A wide photograph of the Sun Temple Konark, emphasizing the immense scale of the surviving audience hall.",
        "A photo showing the structural details of the Sun Temple Konark, including the life-sized statues of elephants and lions.",
        "A photo of the Konark Sun Temple, completely defined by its unique chariot architecture and highly detailed stone wheels."
    ],
    "alai_darwaza": [
        "A photo of the Alai Darwaza, the grand square gatehouse in the Qutub Minar complex.",
        "A wide shot of the Alai Darwaza, showing its stunning contrast of red sandstone and white marble.",
        "A close-up photo of the Alai Darwaza, highlighting the intricately carved Islamic geometric patterns and Arabic calligraphy.",
        "A photo of the Alai Darwaza, focusing on its prominent horseshoe-shaped true arches.",
        "An architectural photograph of the Alai Darwaza, featuring its shallow, wide true dome resting on a square base.",
        "A tourist photo of the Alai Darwaza, capturing the ornate entrance gateway to the Quwwat-ul-Islam Mosque.",
        "A photo of the exterior of Alai Darwaza, showing the delicately carved marble lattice screens in the arched windows.",
        "A detail shot of the Alai Darwaza, focusing on the lotus bud fringes along the intrados of the arches.",
        "A photo of the Alai Darwaza within the Qutub complex, highlighting early Indo-Islamic architecture.",
        "A high-quality image of the Alai Darwaza, emphasizing the rich red stone walls heavily inlaid with white marble bands.",
        "A photo of the Alai Darwaza, defined by its perfectly symmetrical square layout and domed roof.",
        "A close-up photograph of the deeply incised stucco and stone carvings on the facade of the Alai Darwaza.",
        "A wide photograph of the Alai Darwaza, showcasing its position as a monumental southern gateway.",
        "A photo showing the interior arches and squinches of the Alai Darwaza that support its dome.",
        "A photo of the Alai Darwaza, instantly recognizable by its red and white striped archways and detailed Islamic stonework."
    ],
        "alai_minar": [
        "A photo of the Alai Minar, the massive unfinished rubble masonry tower in Delhi.",
        "A wide shot of the Alai Minar, showing its wide, unclad stone base intended to rival the Qutub Minar.",
        "A close-up of the rough, exposed rubble and mortar construction of the incomplete Alai Minar.",
        "A photo of the truncated Alai Minar, a standalone monument with no exterior carvings or sandstone facing.",
        "An architectural photograph of the Alai Minar's immense circular base standing in the Qutub complex.",
        "A tourist photo of the Alai Minar, capturing the sheer scale of the abandoned medieval tower project.",
        "A photo of the Alai Minar exterior, characterized strictly by its jagged, unfinished rock texture.",
        "A detail shot of the thick, sloping rubble walls of the uncompleted Alai Minar.",
        "A photo of the Alai Minar, highlighting the absence of any architectural arches, domes, or polished stone.",
        "A high-quality image of the Alai Minar, the 24-meter tall unfinished core of an Islamic victory tower.",
        "A photo of the Alai Minar, distinguishing it from completed minarets by its raw, stepped masonry construction.",
        "A close-up photograph of the weathered, uneven stone blocks making up the Alai Minar.",
        "A wide photograph of the Alai Minar, emphasizing its stout, heavy proportion compared to surrounding structures.",
        "A photo showing the structural core of the Alai Minar, completely devoid of red sandstone or marble inlay.",
        "A photo of the Alai Minar, strictly recognized as a massive, incomplete, circular stone ruin."
    ],
    "basilica_of_bom_jesus": [
        "A photo of the Basilica of Bom Jesus in Goa, featuring its iconic unplastered reddish-brown laterite stone facade.",
        "A wide shot of the Basilica of Bom Jesus, showing its grand Portuguese Baroque architectural style.",
        "A close-up of the Basilica of Bom Jesus, highlighting the classical pillars and carved basalt details on the exterior.",
        "A photo of the Basilica of Bom Jesus, focusing on the prominent IHS Jesuit monogram carved into the main pediment.",
        "An architectural photograph of the Basilica of Bom Jesus, featuring a three-story facade with Corinthian columns.",
        "A tourist photo of the Basilica of Bom Jesus, capturing the exposed brick-like laterite exterior unique among Goan churches.",
        "A photo of the Basilica of Bom Jesus exterior, showing the intricate stone carving around the main wooden doors.",
        "A detail shot of the Basilica of Bom Jesus, focusing on the ornate buttresses and flying arches.",
        "A photo of the Basilica of Bom Jesus interior, highlighting the gilded altars and the silver casket of St. Francis Xavier.",
        "A high-quality image of the Basilica of Bom Jesus, a monumental Christian church built from dark laterite stone.",
        "A landscape photo of the Basilica of Bom Jesus, distinguishing it from white-washed Goan churches by its raw stone color.",
        "A close-up photograph of the triangular pediment crowning the facade of the Basilica of Bom Jesus.",
        "A wide photograph of the Basilica of Bom Jesus, emphasizing its asymmetrical layout with the attached professed house.",
        "A photo showing the intricate Renaissance and Baroque sculptural elements on the facade of the Basilica of Bom Jesus.",
        "A photo of the Basilica of Bom Jesus, perfectly defined by its unplastered laterite exterior and deep Catholic history."
    ],
    "charminar": [
        "A photo of the Charminar in Hyderabad, featuring its square structure and four towering, ornate minarets.",
        "A wide shot of the Charminar, standing at the center of a bustling market intersection.",
        "A close-up of the Charminar, highlighting the delicate stucco floral motifs and Islamic arches.",
        "A photo of the Charminar, focusing on the four grand arches facing the cardinal directions.",
        "An architectural photograph of the Charminar, showing the double-story galleries and the mosque on the top floor.",
        "A tourist photo of the Charminar, capturing the monument built from granite, limestone, and pulverized marble.",
        "A photo of the Charminar exterior, featuring the distinctive clocks placed above each of the four main arches.",
        "A detail shot of the Charminar, focusing on the petal-shaped domes and finials topping the four minarets.",
        "A photo of the Charminar complex, highlighting its Qutb Shahi architectural style and prominent balconies.",
        "A high-quality image of the Charminar, showing the intricate balustrades and arcades spanning between the minarets.",
        "A photo of the Charminar, distinguishing itself with four identical facades and a perfectly symmetrical square plan.",
        "A close-up photograph of the winding spiral staircases visible through the arched openings of the Charminar minarets.",
        "A wide photograph of the Charminar, emphasizing its monumental scale above the busy streets of Laad Bazaar.",
        "A photo showing the structural details of the Charminar, with highly decorated cornices and brackets.",
        "A photo of the Charminar, completely defined by its four imposing archways and four heavily decorated corner minarets."
    ],
    "golden temple": [
        "A photo of the Golden Temple in Amritsar, featuring its brilliant gold-leaf covered upper floors reflecting in the water.",
        "A wide shot of the Golden Temple, showing the main Harmandir Sahib shrine surrounded by the large Amrit Sarovar holy pool.",
        "A close-up of the Golden Temple, highlighting the white marble lower walls adorned with intricate floral pietra dura inlay.",
        "A photo of the Golden Temple, focusing on the causeway bridge leading directly to the main sanctum.",
        "An architectural photograph of the Golden Temple, featuring the blend of Hindu Rajput and Indo-Islamic Sikh architecture.",
        "A tourist photo of the Golden Temple, capturing the massive gilded dome shaped like an inverted lotus flower.",
        "A photo of the Golden Temple exterior, showcasing the multiple golden chhatris and cupolas lining the roof.",
        "A detail shot of the Golden Temple, focusing on the detailed repoussé work on the gilded copper panels.",
        "A photo of the Golden Temple complex, highlighting the white marble parikrama pathway surrounding the central water body.",
        "A high-quality image of the Golden Temple, glowing warmly under sunlight against the white marble backdrop.",
        "A photo of the Golden Temple, strictly distinguished by its gold-plated upper half sitting above a white marble base.",
        "A close-up photograph of the ornate doorways and golden balconies of the Harmandir Sahib.",
        "A wide photograph of the Golden Temple, emphasizing its central position floating in the middle of a sacred rectangular pool.",
        "A photo showing the architectural details of the Golden Temple, including the intricately decorated Darshani Deori archway.",
        "A photo of the Golden Temple, instantly recognizable by its shimmering gold facade, marble foundation, and surrounding holy waters."
    ],
    "iron_pillar": [
        "A photo of the Iron Pillar of Delhi, a rust-resistant ancient metallic column.",
        "A wide shot of the Iron Pillar standing in the courtyard of the Quwwat-ul-Islam Mosque.",
        "A close-up of the ancient Sanskrit Brahmi inscriptions carved into the dark metal of the Iron Pillar.",
        "A photo of the Iron Pillar, focusing on its decorative, fluted bell capital at the very top.",
        "An architectural photograph showing the freestanding, dark metallic Iron Pillar against the surrounding stone ruins.",
        "A tourist photo of the Iron Pillar, capturing its smooth, rust-free surface despite centuries of exposure.",
        "A detail shot of the base of the Iron Pillar of Delhi embedded firmly in the stone courtyard.",
        "A photo of the ancient Indian metallurgical marvel known as the Iron Pillar.",
        "A high-quality image of the Iron Pillar, distinct for its pure iron composition rather than carved stone.",
        "A photo showing the full length of the 7-meter tall solid Iron Pillar in the Qutub complex.",
        "A close-up photograph of the Gupta-era script etched heavily into the Iron Pillar.",
        "A wide photograph of the Iron Pillar, a dark, narrow metallic shaft contrasting with the red sandstone background.",
        "A photo of the historic Iron Pillar, completely defined by its ancient iron forging and complete lack of rust.",
        "A photo of the decorative, ribbed top finial of the Iron Pillar of Delhi.",
        "A photo of the Iron Pillar, an ancient, dark metal standing column from the 4th century."
    ],
    "jamali_kamali_tomb": [
        "A photo of the Jamali Kamali Tomb, featuring its ornate red sandstone and white marble exterior.",
        "A wide shot of the Jamali Kamali Mosque and Tomb complex in the Mehrauli Archaeological Park.",
        "A close-up of the Jamali Kamali Tomb ceiling, highlighting the stunning red and blue painted stucco medallions.",
        "A photo of the interior chamber of the Jamali Kamali Tomb, filled with intricate Quranic inscriptions and poetry.",
        "An architectural photograph of the flat-roofed tomb chamber of Jamali Kamali decorated with colored tiles.",
        "A tourist photo of the Jamali Kamali Mosque, capturing the prayer hall's five arches and single central dome.",
        "A photo of the beautifully painted plasterwork inside the small, enclosed Jamali Kamali Tomb.",
        "A detail shot focusing on the delicate incised colored plaster inside the Jamali Kamali Tomb chamber.",
        "A photo of the Jamali Kamali complex, highlighting the early Mughal architectural transition in Delhi.",
        "A high-quality image of the Jamali Kamali Tomb interior, heavily ornamented with blue and red geometric tilework.",
        "A close-up photograph of the marble graves inside the highly decorated, dark chamber of the Jamali Kamali Tomb.",
        "A wide photograph showing the walled courtyard of the Jamali Kamali Mosque.",
        "A photo showing the arched mihrab and red sandstone masonry of the Jamali Kamali Mosque.",
        "A photo of the Jamali Kamali Tomb, recognized for its exceptionally colorful and preserved interior painted ceiling.",
        "A photo of the Jamali Kamali Tomb and mosque, a distinct 16th-century red stone and marble structural complex."
    ],
    "lotus_temple": [
        "A photo of the Lotus Temple in Delhi, featuring its modern architecture shaped entirely like a blooming lotus flower.",
        "A wide shot of the Lotus Temple, showing the 27 free-standing white marble-clad petals forming the structure.",
        "A close-up of the smooth white marble surface of the Lotus Temple's curved exterior petals.",
        "A photo of the Lotus Temple, completely surrounded by its nine clear blue reflecting water pools.",
        "An architectural photograph of the modern Bahá'í House of Worship known as the Lotus Temple.",
        "A tourist photo of the Lotus Temple, capturing its stark white floral shape rising against the sky.",
        "A photo of the Lotus Temple exterior, focusing on the overlapping layers of concrete and marble petals.",
        "A landscape photo of the Lotus Temple sitting beautifully amidst green gardens and blue water features.",
        "A photo showing the entrance pathways bridging the pools to enter the pure white Lotus Temple.",
        "A high-quality image of the Lotus Temple, defined by its complete lack of any traditional domes, minarets, or carvings.",
        "A wide photograph of the Lotus Temple illuminating brightly at dusk.",
        "A close-up photograph of the geometric, ribbed ceiling inside the central hall of the Lotus Temple.",
        "A photo of the Bahá'í Lotus Temple, instantly recognizable by its pure white, modern floral expressionist architecture.",
        "A photo showing the sweeping curves and sharp upward points of the Lotus Temple's marble petals.",
        "A photo of the Lotus Temple, a massive white modern structure built perfectly in the shape of a half-opened lotus."
    ],
    "mysore_palace": [
        "A photo of the Mysore Palace, an immense Indo-Saracenic royal building made of fine grey granite.",
        "A wide shot of the Mysore Palace, featuring its central five-story tower topped with a gilded dome.",
        "A close-up of the Mysore Palace, highlighting its deep pink marble domes capping the square corner towers.",
        "A photo of the Mysore Palace at night, illuminated brilliantly by nearly 100,000 incandescent light bulbs.",
        "An architectural photograph of the Mysore Palace, showing its grand blend of Hindu, Rajput, and Gothic styles.",
        "A tourist photo of the Mysore Palace, capturing the grand arched facade supported by tall, ornate pillars.",
        "A photo of the interior Public Durbar Hall of the Mysore Palace, filled with beautifully sculpted and painted columns.",
        "A detail shot focusing on the intricately carved rosewood doors and stained glass ceilings of the Mysore Palace.",
        "A photo of the sprawling Mysore Palace complex, showing the vast courtyard and red cupolas.",
        "A high-quality image of the Mysore Palace, dominated by its majestic grey stone walls and pinkish-red domes.",
        "A wide photograph of the Mysore Palace, emphasizing its royal scale and highly decorated scalloped arches.",
        "A close-up photograph of the golden finial atop the main central stone dome of the Mysore Palace.",
        "A photo showing the Kalyana Mantapa pavilion inside the Mysore Palace with its octagonal stained-glass roof.",
        "A photo of the Mysore Palace, universally recognized by its stunning nighttime illumination outlining the entire building.",
        "A photo of the grand Mysore Palace in Karnataka, strictly characterized by its grey granite structure and vibrant pink domes."
    ],
        "qutub_minar": [
        "A photo of the Qutub Minar in Delhi, featuring its soaring red sandstone fluted tower.",
        "A wide shot of the Qutub Minar, showing the five distinct storeys of the tapering Islamic victory monument.",
        "A close-up of the Qutub Minar, highlighting the intricate bands of Arabic calligraphy carved into the red sandstone.",
        "A photo of the Qutub Minar, focusing on the highly ornate corbelled stone balconies separating each tier.",
        "An architectural photograph of the Qutub Minar, showing the alternating angular and rounded flutes on its exterior.",
        "A tourist photo of the Qutub Minar, capturing its monumental scale rising above the surrounding archaeological ruins.",
        "A photo of the Qutub Minar's upper storeys, distinguishing the transition from red sandstone to white marble at the very top.",
        "A detail shot of the Qutub Minar, focusing on the deep, sharp geometric carvings on the ribbed column.",
        "A photo of the Qutub Minar complex, highlighting the towering minaret against the sky.",
        "A high-quality image of the Qutub Minar, the tallest brick and stone minaret in the world.",
        "A landscape photo of the Qutub Minar, standing isolated and complete unlike the neighboring Alai Minar.",
        "A close-up photograph of the stalactite-like muqarnas corbelling supporting the balconies of the Qutub Minar.",
        "A wide photograph of the Qutub Minar, emphasizing its slight tilt and massive base diameter.",
        "A photo showing the structural details of the Qutub Minar, an early masterpiece of Indo-Islamic architecture.",
        "A photo of the Qutub Minar, universally recognized by its tall, ribbed, intricately carved red sandstone profile."
    ],
    "tajmahal": [
        "A photo of the Taj Mahal in Agra, featuring its perfect symmetry and glowing white Makrana marble construction.",
        "A wide shot of the Taj Mahal, showing the massive white onion dome flanked by four detached minarets.",
        "A close-up of the Taj Mahal, highlighting the exquisite pietra dura floral inlay work using semi-precious stones.",
        "A photo of the Taj Mahal viewed from the Charbagh gardens, perfectly reflecting in the long central water channel.",
        "An architectural photograph of the Taj Mahal, showing the massive central iwan archway framed by Quranic calligraphy.",
        "A tourist photo of the Taj Mahal, capturing the iconic Mughal mausoleum glowing under the sunlight.",
        "A photo of the exterior of the Taj Mahal, featuring the chhatris (domed kiosks) surrounding the main central dome.",
        "A detail shot of the Taj Mahal, focusing on the delicate, translucent white marble lattice screens (jalis).",
        "A photo of the Taj Mahal complex, highlighting the contrast between the white marble tomb and the red sandstone flanking mosques.",
        "A high-quality image of the Taj Mahal, emphasizing its flawless proportions and raised square marble plinth.",
        "A photo of the Taj Mahal, distinguishing it strictly as an all-white marble structure unlike Humayun's Tomb.",
        "A close-up photograph of the lotus finial topping the massive central dome of the Taj Mahal.",
        "A wide photograph of the Taj Mahal taken from across the Yamuna river.",
        "A photo showing the structural details of the four cylindrical minarets guarding the corners of the Taj Mahal platform.",
        "A photo of the Taj Mahal, universally recognized as the ultimate masterpiece of white marble Mughal architecture."
    ],
    "tanjavur temple": [
        "A photo of the Brihadeeswarar Temple in Thanjavur, featuring its massive pyramidal granite vimana tower over the main shrine.",
        "A wide shot of the Thanjavur Temple, showing the immense scale of this 11th-century Chola dynasty masterpiece.",
        "A close-up of the Thanjavur Temple, highlighting the intricate sculptures carved directly into the hard granite blocks.",
        "A photo of the Thanjavur Temple courtyard, focusing on the giant monolithic Nandi bull facing the main sanctum.",
        "An architectural photograph of the Thanjavur Temple, showing the towering 13-tiered vimana culminating in a massive monolithic stone cupola.",
        "A tourist photo of the Brihadeeswarar Temple, capturing the grand Dravidian stone architecture rising from the flat landscape.",
        "A photo of the exterior of the Thanjavur Temple, featuring the detailed stone figures of Shiva carved into the tower niches.",
        "A detail shot of the Thanjavur Temple, focusing on the massive stone blocks fitted perfectly without mortar.",
        "A photo of the Thanjavur Temple complex, highlighting the long pillared corridors enclosing the vast courtyard.",
        "A high-quality image of the Brihadeeswarar Temple, emphasizing its unique design where the central vimana is taller than the gateway gopurams.",
        "A landscape photo of the Thanjavur Temple, an architectural marvel built entirely from interlocking granite.",
        "A close-up photograph of the giant, rounded stone sikhara resting at the very top of the Thanjavur Temple tower.",
        "A wide photograph of the Thanjavur Temple, showcasing its fortified walls and moat.",
        "A photo showing the heavily carved pillared mandapas leading into the main shrine of the Thanjavur Temple.",
        "A photo of the Thanjavur Temple, instantly recognizable by its colossal, step-pyramid granite tower built by Raja Raja Chola."
    ],
    "victoria memorial": [
        "A photo of the Victoria Memorial in Kolkata, featuring its grand white Makrana marble Indo-Saracenic colonial architecture.",
        "A wide shot of the Victoria Memorial, showing its massive central dome and symmetrical wings situated in vast formal gardens.",
        "A close-up of the Victoria Memorial, highlighting the large bronze Angel of Victory statue mounted on the apex of the central dome.",
        "A photo of the Victoria Memorial, focusing on the blend of British classical architecture with Mughal-style domed chhatris.",
        "An architectural photograph of the Victoria Memorial, showing its grand colonnaded terraces and white marble facades.",
        "A tourist photo of the Victoria Memorial, capturing the sprawling, palace-like museum reflecting in the foreground water pools.",
        "A photo of the exterior of the Victoria Memorial, featuring the intricate marble statues and allegorical sculptures adorning the roofline.",
        "A detail shot of the Victoria Memorial, focusing on the classical Corinthian columns contrasting with Indian architectural elements.",
        "A photo of the Victoria Memorial complex, highlighting its sheer scale and brilliant white appearance against the Maidan.",
        "A high-quality image of the Victoria Memorial, distinguishing it from Mughal tombs by its prominent Western classical symmetry and statues.",
        "A landscape photo of the Victoria Memorial, surrounded by lush green lawns and palm trees in West Bengal.",
        "A close-up photograph of the soaring white marble corner towers and cupolas of the Victoria Memorial.",
        "A wide photograph of the Victoria Memorial from across the lake, showcasing its majestic, palace-like reflection.",
        "A photo showing the structural details of the Victoria Memorial's massive central arched portico.",
        "A photo of the Victoria Memorial, perfectly defined by its pristine white marble, central dome, and towering bronze angel."
    ]
}